SELECT * FROM booking_status;
SELECT * FROM bookings;
SELECT * FROM employee;
SELECT * FROM guests;
SELECT * FROM hostels;
SELECT * FROM place_type;
SELECT * FROM positions;
SELECT * FROM places;
SELECT * FROM room;
SELECT * FROM service_hostel;
SELECT * FROM service_rendered;
SELECT * FROM services;

drop table if EXISTS BOOKINGS;
drop table if EXISTS BOOKING_STATUS;
drop table if EXISTS PLACES;
drop table if EXISTS PLACE_TYPE;
drop table if EXISTS ROOM;
drop table if EXISTS SERVICE_RENDERED;
drop table if EXISTS GUESTS;
drop table if EXISTS EMPLOYEE;
drop table if EXISTS POSITIONS;
drop table if EXISTS SERVICE_HOSTEL;
drop table if EXISTS SERVICES;
drop table if EXISTS HOSTELS;


--Таблица 1. Хостел
CREATE TABLE HOSTELS(
	HOSTEL_ID UUID PRIMARY KEY,
	ADDRESS VARCHAR(100) NOT NULL,
	PHONE VARCHAR(11) NOT NULL,
	AVAILABLE BOOLEAN       	
);


--Таблица 2. Комната
CREATE TABLE ROOM (
	ROOM_ID UUID PRIMARY KEY, 
	GENDER CHAR(1) CHECK(GENDER  in('М', 'Ж', 'Н')) default 'Н',
	CAPACITY SMALLINT,
	AVAILAVILITY BOOLEAN,
	HOSTEL_ID UUID REFERENCES HOSTELS( HOSTEL_ID )
);

--Таблица 3. Тип места
CREATE TABLE PLACE_TYPE(
	PLACE_TYPE_ID  UUID  PRIMARY KEY, 
	TYPE VARCHAR(100),
	PRICE MONEY
);

--Таблица 4. Места
CREATE TABLE PLACES (
	PLACE_ID UUID PRIMARY KEY,
	PLACE_TYPE_ID UUID REFERENCES PLACE_TYPE ( PLACE_TYPE_ID ),
	ROOM_ID UUID REFERENCES ROOM ( ROOM_ID )
);


--Таблица 6. Статус брони
CREATE TABLE BOOKING_STATUS (
	BK_ID UUID PRIMARY KEY,
	STATUS CHAR(1) CHECK(STATUS  in('A', 'B', 'C')) default 'A',
	DESCRIPTION VARCHAR(100)
);


--Таблица 8. Должности
CREATE TABLE POSITIONS(
	POSITION_ID UUID  PRIMARY KEY, 
	NAME VARCHAR(50),
	SALARY MONEY
);

--Таблица 7. Сотрудники
CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID UUID PRIMARY KEY,
	PASSPORT VARCHAR(10) NOT NULL,
	SURNAME VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	FATHERNAME VARCHAR(20) NOT NULL,
	GENDER CHAR(1) CHECK(GENDER  in('М', 'Ж', 'Н')) default 'Н',
	ADDRESS VARCHAR(100),
	BIRTHDATE DATE NOT NULL,
	POSITION_ID UUID REFERENCES POSITIONS( POSITION_ID  ),
	PHONE_NUMBER VARCHAR(11),
	HOSTEL_ID UUID REFERENCES HOSTELS( HOSTEL_ID  )
);


--Таблица 9. Гости
CREATE TABLE GUESTS(
	GUEST_ID UUID  PRIMARY KEY, 
	PASSPORT VARCHAR(10),
	SURNAME VARCHAR(20), 
	NAME VARCHAR(20),
	FATHERNAME VARCHAR(20),
	SEX CHAR(1) CHECK(SEX in('М', 'Ж', 'Н')) default 'Н',
	ADDRESS VARCHAR(100),
	BIRTHDATE DATE, 
	PHONE_NUMBER VARCHAR(11),
	EMAIL VARCHAR(30)
);

--Таблица 5. Бронирования
CREATE TABLE BOOKINGS (
	PB_ID UUID  PRIMARY KEY, 
	ARRIVAL_DATE TIMESTAMP WITH TIME ZONE,
	CHECKOUT_DATE TIMESTAMP WITH TIME ZONE, 
	MONEY_TOTAL MONEY,
	BK_ID UUID REFERENCES BOOKING_STATUS( BK_ID  ),
	GUEST_ID UUID REFERENCES GUESTS( GUEST_ID  ),
	PLACE_ID UUID REFERENCES PLACES( PLACE_ID  )
);

--Таблица 10. Услуги
CREATE TABLE SERVICES(
	SERVICE_ID UUID  PRIMARY KEY, 
	PRICE MONEY,
	DESCRIPTION VARCHAR(100)
);


--Таблица 11. Услуги в хостеле
CREATE TABLE SERVICE_HOSTEL(
	SH_ID UUID  PRIMARY KEY, 
	SERVICE_ID  UUID REFERENCES SERVICES( SERVICE_ID ),
	HOSTEL_ID  UUID REFERENCES HOSTELS( HOSTEL_ID )
);


--Таблица 12. Оказанные услуги
CREATE TABLE SERVICE_RENDERED (
	SR_ID UUID PRIMARY KEY,
	AMOUNT SMALLINT,
	STATUS CHAR(1) CHECK(STATUS in('A', 'B', 'C')) default 'A',
	TIME TIMESTAMP WITH TIME ZONE,
	EMPLOYEE_ID UUID REFERENCES EMPLOYEE( EMPLOYEE_ID ),
	SH_ID  UUID REFERENCES SERVICE_HOSTEL( SH_ID ),
	GUEST_ID UUID REFERENCES GUESTS( GUEST_ID ),
	TOTAL_PRICE MONEY
);