# Generated by Django 4.1.3 on 2022-11-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_id', models.UUIDField()),
                ('status', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.UUIDField()),
                ('passport', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.UUIDField()),
                ('passport', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_id', models.UUIDField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('AVAILABLE', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type_id', models.UUIDField()),
                ('type', models.CharField(max_length=100)),
                ('PRICE', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.UUIDField()),
                ('name', models.CharField(max_length=50)),
                ('salary', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_id', models.UUIDField()),
                ('HOSTEL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.hostels')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.UUIDField()),
                ('price', models.SmallIntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRendered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_id', models.UUIDField()),
                ('amount', models.SmallIntegerField()),
                ('status', models.CharField(max_length=1)),
                ('time', models.DateTimeField()),
                ('total_price', models.SmallIntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.employee')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.guests')),
                ('sh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.servicehostel')),
            ],
        ),
        migrations.AddField(
            model_name='servicehostel',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.services'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField()),
                ('gender', models.CharField(max_length=1)),
                ('capacity', models.SmallIntegerField()),
                ('availability', models.BooleanField()),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.hostels')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.UUIDField()),
                ('place_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.placetype')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.room')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='hostel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.hostels'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.positions'),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb_id', models.UUIDField()),
                ('arrival_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('money_total', models.SmallIntegerField()),
                ('bk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.bookingstatus')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.guests')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.places')),
            ],
        ),
    ]
