# Generated by Django 4.1.4 on 2022-12-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
