# Generated by Django 4.1.4 on 2022-12-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='LoginUsers',
        ),
    ]
